### ISSUE TITLE
Mail notifications

### ISSUE THREAD

**Issue by WiktorMarszalkowski** [V0ldek/GameBoard#2]
As a user with an existing account, I want to get notifications about invitations to events onto my account's email, without needing to log into this app.

**Comment by V0ldek** [comment]
As part of this US, update the authentication system to require email confirmation for a sign in and allow password resets. That will require sending emails with generated tokens.

[Consult the MSDN on this one](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.2&tabs=visual-studio).

**Comment by zirrock** [comment]
Mail notification function will take 2 arguments :

- recipient list
- Message object

The function will generate a message using the details passed in Message following one of the patterns.

Those patterns are :

- invitation
- confirmation
- cancellation
- account confirmation
- password reset
