### ISSUE TITLE
CreateIdentitySchema migration is invalid.

### ISSUE THREAD

**Issue by V0ldek** [V0ldek/GameBoard#27]
The migration files were changed by hand, which led to a mistake - don't do that, all model changes should be done in `GameBoardDbContext.OnModelCreating`. Move the 512 MaxLength constraints there, as well as any other changes that were manually done in the `.Designer` and `ModelSnapshot` and recreate the migration. To verify that it's correct, get to @WiktorMarszalkowski to verify that he has no problems creating his migrations.

**Comment by matus3000** [comment]
Done.
